# https://reuse.software/

version = 1

[[annotations]]
path = "tt-white.png"
SPDX-FileCopyrightText = "© 2019 Alexander Kromm <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tt-frame.png"
SPDX-FileCopyrightText = "© 2025 Alexander Kromm <mmaulwurff@gmail.com>"
SPDX-License-Identifier = "CC0-1.0"
