# SPDX-FileCopyrightText: Â© 2026 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

[tool.ruff]
line-length = 85
indent-width = 2
target-version = "py313"

[tool.ruff.format]
quote-style = "single"
