# SPDX-FileCopyrightText: Â© 2025 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

# GitHub Action for dev builds
# https://docs.github.com/en/actions

name: dev-builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Set up system dependencies
        run: |
          nix-build tools/shell.nix

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('tools/shell.nix') }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'tools/requirements-dev.txt'

      - name: Set up Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements-dev.txt;

      - name: Build
        run: |
          nix-shell tools/shell.nix --command "scons Pk3All"

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: |
            build/*.pk3
            !build/Typist.pk3
