# SPDX-FileCopyrightText: Â© 2025 Alexander Kromm <mmaulwurff@gmail.com>
# SPDX-License-Identifier: CC0-1.0

# GitHub Action for dev builds
# https://docs.github.com/en/actions

name: dev-builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we want
# to allow these production deployments to complete.
concurrency:
  group: 'dev-build'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Cache Nix
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('tools/shell.nix') }}

      - name: Install system dependencies
        run: |
          nix-build tools/shell.nix

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: 'tools/requirements-dev.txt'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements-dev.txt;

      - name: Build
        run: |
          nix-shell tools/shell.nix --command "scons Pk3All"

      - name: Upload distributions
        uses: actions/upload-artifact@v6
        with:
          name: doom-toolbox
          path: |
            build/*.pk3
            !build/Typist.pk3

      - name: Clean up build
        run: |
          rm -r build

      - name: Export to HTML
        run: |
          nix-shell tools/shell.nix --command "scons HtmlAll"

      - name: Configure pages
        uses: actions/configure-pages@v5

      - name: Upload pages
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: '.'

      - name: Deploy pages to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
